services:
   postgres:
      image: postgres:16
      container_name: postgres_db
      env_file:
         - ./app/.env
      restart: always
      ports:
         - 5432:5432
      volumes:
         - postgres_data:/var/lib/postgresql/data
      networks:
         - db_network

volumes:
   postgres_data:

networks:
   db_network:
